# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#   schedule:
#     - cron: '0 0 * * *'
    push:
      branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3' 
    - name: Run the script
      with:
        access_token: ${{ secrets.access_token }}
        access_token_secret: ${{ secrets.access_token_secret }}
      run: Rscript To_be_run_daily.R $access_token $access_token_secret

